version: '3'

volumes:
  database:

services:
  dog_blog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: dog_blog
    container_name: dog_blog
    working_dir: /app
    volumes:
      - database:/app/database
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

#  nginx:
#    build:
#      context: .
#      dockerfile: compose/production/nginx/Dockerfile
#    image: dog_blog_nginx
#    container_name: dog_blog_nginx
#    volumes:
#      - static:/apps/dogBlog/static
#    ports:
#      - "80:80"
#      - "443:443"